### ISSUE TITLE
TODOS

### ISSUE THREAD

**Issue by louis030195** [stellar-amenities/assistants#1]
- [ ] general repo
  - [x] ci cd
  - [ ] good readme
  - [ ] instructions contribute etc
  - [ ] templates
  - [ ] consider generating models like openai based on the yaml thing
  - [ ] tests that run on openai api then on open source assistants and compare results
  - [x] properly segmented by users
  - [ ] split assistants-core code in smaller chunks
  - [x] docker stuff
  - [x] software 3.0 stuff
    - [x] basically openai assistants takes automatic decisions on tools to use - gotta implement something smooth that well replicate (need some more data on the experience if anyone is big user of their api?)
  - [ ] [all the entrypoints](https://platform.openai.com/docs/api-reference/assistants)
    - [x] POST /assistants - Create a new assistant.
    - [x] GET /assistants/{assistant_id} - Retrieve a specific assistant by its ID.
    - [x] GET /assistants - List all assistants.
    - [x] POST /assistants/{assistant_id} - Update a specific assistant.
    - [x] DELETE /assistants/{assistant_id} - Delete a specific assistant.
    - [x] POST /threads - Create a new thread.
    - [x] GET /threads/{thread_id} - Retrieve a specific thread by its ID.
    - [x] GET /threads - List all threads.
    - [x] POST /threads/{thread_id} - Update a specific thread.
    - [x] DELETE /threads/{thread_id} - Delete a specific thread.
    - [x] POST /threads/{thread_id}/messages - Add a new message to a thread.
    - [x] GET /threads/{thread_id}/messages/{message_id} - Retrieve a specific message by its ID.
    - [x] GET /threads/{thread_id}/messages - List all messages in a thread.
    - [x] DELETE /threads/{thread_id}/messages/{message_id} - Delete a specific message.
    - [x] POST /threads/{thread_id}/runs - Create a run.
    - [x] GET /threads/{thread_id}/runs/{run_id} - Retrieve a run.
    - [x] POST /threads/{thread_id}/runs/{run_id} - Modify a run.
    - [x] GET /threads/{thread_id}/runs - List runs.
    - [x] POST /threads/{thread_id}/runs/{run_id}/submit_tool_outputs - Submit tool outputs to run.
    - [ ] POST /threads/{thread_id}/runs/{run_id}/cancel - Cancel a run.
    - [ ] POST /threads/runs - Create thread and run.
    - [ ] GET /threads/{thread_id}/runs/{run_id}/steps/{step_id} - Retrieve run step.
    - [ ] GET /threads/{thread_id}/runs/{run_id}/steps - List run steps.
    - [x] POST /files - Upload a file.
    - [ ] GET /files/{file_id} - Fetch a file's details.
    - [ ] POST /files/{file_id} - Update a file's details.
    - [ ] DELETE /files/{file_id} - Delete a file.
    - [ ] GET /files - List all files.
    - [ ] GET /files/{file_id}/download - Download a file.
  - [ ] 10/10 error handling (atm 4/10)
    - [ ] [run error](https://platform.openai.com/docs/api-reference/runs)
    - [ ] general error handling
      - [ ] shouldnt crash the api when no rows are returned :) (unit test!!)
  - [ ] all the properties in models used properly [like openai](https://platform.openai.com/docs/api-reference/assistants)
- [x] [end to end overview](https://platform.openai.com/docs/assistants/overview)
  - [x] logic
  - [x] api
  - [x] models
- [ ] retrieval
  - [ ] examples
    - [x] curl anthropic hello world
    - [x] curl mistral hello world
    - [x] js retrieval anthropic hello world
    - [ ] nextjs hello world
  - [ ] annotations 
  - [ ] vector
    - [ ] in pg?
    - [ ] in redis?
    - [ ] external vector db? (fuck additional infra :D)
  - [ ] full text
  - [ ] sql generation / execution (out of project scope? could be an example)
- [x] Files
  - [x] pdfs & co
  - [ ] images, jpg ...
  - [ ] video
  - [x] txt
- [ ] code interpreter
  - [ ] suggest in a new dir like "assistants-code-interpreter" because i assume there will be a bunch of specific deps to execute code etc, scalable thing - maybe some copy paste from [there](https://github.com/KillianLucas/open-interpreter)
- [x] function calling
  - [x] anthropic
  - [x] openai
  - [x] open source llm
  - [x] basic tests
  - [ ] bunch of tests for all edge cases
  - [ ] examples
    - [x] end-to-end thru curl anthropic
    - [x] end-to-end intel neural-chat nodejs
    - [ ] end-to-end curl mistral
    - [ ] end-to-end curl mistral retrieval + function calling
- [ ] LLMs
  - [x] OpenAI (useful for open source LLMs deployed with OpenAI like API)
  - [x] Anthropic
  - [x] open source
  - [x] document how to run LLMs (vLLM, etc.)
    - [x] fastchat (mac/cpu)
    - [ ] perplexity
    - [ ] vllm (gpu)
    - [ ] one click cloud
    - [ ] k8s gpu
    - [ ] modal
    - [ ] replicate
    - [ ] [skypilot](https://docs.mistral.ai/cloud-deployment/skypilot/)
- [ ] infra
  - [ ] one-click to deploy everything somewhere in ur infra in less than 10 seconds
  - [ ] enterprise support (k8s)
    - [x] v0 
    - [ ] readme example k8s in < 1 min
  - [ ] on the edge (not arm!) without internet access
- [ ] performance
  - [ ] benches
  - [ ] prompt templates e.g. how X or Y system prompt / template performs on Z or W model. Basically need a list of system prompt and prompt template and inputs and a list of LLM to run test against. Ideally we only run on open source LLM, need high performance maybe, ideally some spare GPUs somewhere

**Comment by louis030195** [comment]
Few things that could be even better than OpenAI Assistants API but out of scope ATM:
- OpenAI Assistants API assume an assistant always use the same model, but the future will use many different LLMs, for different domain, speed and quality requirements.

**Comment by transitive-bullshit** [comment]
This project looks awesome 💪 

Maybe we can join forces? https://github.com/transitive-bullshit/OpenOpenAI

Prolly the most relevant part of my project is that all of the API routes and input/output types are auto-generated from OpenAI's official OpenAPI spec, so it'll be pretty straightforward to keep them in sync in the future.

**Comment by louis030195** [comment]
@transitive-bullshit This is cool! Let's chat soon https://cal.com/louis030195/d

**Comment by louis030195** [comment]
🚢 @transitive-bullshit now using official openai OpenAPI spec
