### ISSUE TITLE
run & deploy a simple proxy to run anthropic into openai api compatible

### ISSUE THREAD

**Issue by louis030195** [stellar-amenities/assistants#21]
would simplify codebase

overall my guess is nobody care nor use anthropic but useful for testing stuff

**Comment by louis030195** [comment]
bet litellm does that

**Comment by ishaan-jaff** [comment]
litellm supports this ^

**Comment by louis030195** [comment]
@ishaan-jaff would love a PR!

**Comment by louis030195** [comment]
fk anthropic
