### ISSUE TITLE
Example: hello-world-anthropic-knowledge-retrieval gets hanged when uploading a PDF

### ISSUE THREAD

**Issue by GaneshKannusamy** [stellar-amenities/assistants#40]
Error: 

Uploaded file: "27664fc3-ec1e-4a38-88f7-7da916bc9d7c.pdf"
thread 'tokio-runtime-worker' panicked at /Users/xyz/assistants/assistants/assistants-api-communication/src/files.rs:67:62:

error: Utf8Error { valid_up_to: 10, error_len: Some(1) } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by louis030195** [comment]
hey @GaneshKannusamy thanks for testing out!

sorry about that this example was completely outdated but revealed a specific use case with files that I fixed

in general i recommend trying examples with open source LLMs where more focus is invested in

feel free to open another issue or reopen the issue if you face a problem
