### ISSUE TITLE
Request update to: "How it Works – Visual Guide"

### ISSUE THREAD

**Issue by GaneshKannusamy** [stellar-amenities/assistants#42]
"How it Works – Visual Guide" explains Assistants interaction really well, A request is to add the below,

1. Code Interpreter's interaction with AI Service
2. Add the interaction with Open AI SDK/Service
3. There is no interaction with AI Service for tool switching - is this correct ?

**Comment by louis030195** [comment]
I updated! Let me know if it's clearer and answer those questions

**Comment by GaneshKannusamy** [comment]
Looks good, thanks!

**Comment by GaneshKannusamy** [comment]
Diagram updated
