### ISSUE TITLE
Example hello-world-mistral-curl Run status: failed with no reson for failure

### ISSUE THREAD

**Issue by GaneshKannusamy** [stellar-amenities/assistants#45]
1. Example hello-world-mistral-curl Run status: failed with no reson for failure,

Below is the output
{"id":"61d9cb05-989b-4b48-b520-xxxxxxxxx","object":"","created_at":1704030934,"thread_id":"cefa085b-263e-4e3c-a1c5-62699fxxxxxx","assistant_id":"65b76ee5-6223-4383-ae65-d23eecxxxxxx","status":"failed","required_action":null,"last_error":null,"expires_at":null,"started_at":null,"cancelled_at":null,"failed_at":null,"completed_at":null,"model":"","instructions":"Please solve the equation.","tools":[],"file_ids":[],"metadata":{}}

Can we get more reasons of failure in the output and how do we debug these failures ?

2. How do we get the run-id? Is it the output "id" from Step 5: ***Run the Assistant*** ?

**Comment by louis030195** [comment]
Hey sorry for the delay, didn't get notified

1. Thanks I'll try to reproduce. Need to implement more error handling, should be an easy task 

2. It seems to be a run output so the "id" is the id

**Comment by louis030195** [comment]
hey i implemented #46 (better errors) and fixed the tutorial (there was an issue with the model url due to being in the host from the container child)

sorry for this, let me know if you have other issues, happy to help!
