### ISSUE TITLE
"action" tool (function calling on the server)

### ISSUE THREAD

**Issue by louis030195** [stellar-amenities/assistants#59]
#25 prelim

<img width="866" alt="image" src="https://github.com/stellar-amenities/assistants/assets/25003283/b5238821-585e-49cd-9212-f3cdb30fb255">

i.e. same as in chatgpt ui

https://platform.openai.com/docs/actions but for assistant api

**Comment by CakeCrusher** [comment]
@louis030195 
Here is a demo of how I got actions to work with assistant. It consists of the following steps:
1. Provide a OpenAPI spec
2. Generate functions from the spec (in parallel)
2. Generate HTTP request functions from the spec (in parallel)
3. Whenever the function from the OpenAPI spec is called, send the `args` to the generated HTTP request function.
4. Return the results as the tool outputs.
5. Done.

As an action this whole process should happen automatically in the assistant backend.

https://gist.github.com/CakeCrusher/aad0cdb695aea7eca55d31bc801a7f83

**Comment by CakeCrusher** [comment]
The expectation is to be able to pass a tool like so:
```py
client.beta.assistants.create(
    name="Action assistant",
    tools=[
        # ...    
        {
            "type": "action",
            "openapi_spec": """
                openapi: 3.0.0
                ...
            """
        } # this tool will execute autonimously
    ]
)
```

For simplicity here are the features that I think can wait until after the initial release:
- authentication
  - (more so can wait) [multiple authentication schemas](https://platform.openai.com/docs/actions)
- [is consequential flag](https://platform.openai.com/docs/actions)
- [OpenAPI reference mapping](https://swagger.io/docs/specification/using-ref/)

**Comment by louis030195** [comment]
should be easy to implement after merging https://github.com/stellar-amenities/assistants/pull/62

@CakeCrusher

**Comment by louis030195** [comment]
done v0
